### PR TITLE
Remove old version log message

### PR DESCRIPTION
**Pull request by ujwalkumar1995**
Hey @viniarck 
I have raised the PR for the issue #40

### CODE REVIEW

**Comment by viniarck** [comment]
Thanks for this PR @ujwalkumar1995, looks good, the change is very simple. But before I accept this PR, I'll need you to digitally sign the CLA, add extra personal information, fix the linter error and follow the guidelines/templates that kytos-ng org requires https://kytos-ng.github.io/procedures/prs.html#prerequisites.

**Comment by ujwalkumar1995** [comment]
Hey @viniarck 
Have submitted the CLA form.
Let me know if I need to do anything else.

**Comment by viniarck** [comment]
> Hey @viniarck Have submitted the CLA form. Let me know if I need to do anything else.

@ujwalkumar1995 much appreciated, I've just confirmed the CLA signature is all set.

The only thing remaining is to fix this linter error:

> main.py|31:0|Unused log imported from kytos.core (W0611, unused-import) [pylint]

You can find more information about the linter error [directly on Scrutinizer CI execution](https://scrutinizer-ci.com/g/kytos-ng/sdntrace/inspections/9243df6b-baf0-4a2c-8f5e-c22feae761be), when you fix it, it should be a check green check. If you also want to run the linter and tests locally you can run `tox`.

**Comment by ujwalkumar1995** [comment]
Hey @viniarck 
Thank you for pointing that out.
Have fixed it.

**Review by viniarck — APPROVED** [review]
Looks good. Congrats, @ujwalkumar1995. 

If you end up contributing again to kytos-ng org that CLA is valid for all future PRs. 

Have a great day. This PR will get merged soon.

**Pull request merged**
